services:
  - type: web
    name: meetz
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_EXTERNAL_URL
        value: https://meetz.onrender.com
